services:
  hs-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: headscale_db
      POSTGRES_USER: headscale_user
      POSTGRES_PASSWORD: 12345678 # <--- IMPORTANT: CHANGE THIS TO A SECURE PASSWORD!
    volumes:
      - headscale_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-U",
          "headscale_user",
          "-d",
          "headscale_db",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - headscale-net

  hs-A:
    image: headscale-0.23-dev:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: headscale_db
      POSTGRES_USER: headscale_user
      POSTGRES_PASSWORD: 12345678 # <--- IMPORTANT: MUST MATCH THE DB PASSWORD ABOVE!
      POSTGRES_HOST: hs-db
      POSTGRES_PORT: 5432
      HEADSCALE_SERVER_URL: http://hs-0:8080 # URL for clients connecting to this instance
    volumes:
      - ./headscale_config:/etc/headscale # Shared config
      - headscale_data:/var/lib/headscale # Shared data
    ports:
      - "0.0.0.0:8080:8080" # Client port for hs-0
      - "0.0.0.0:9090:9090" # Metrics port
      - "50443:50443" # gRPC port for postman testing
    command: ["headscale", "serve"]
    depends_on:
      hs-db:
        condition: service_healthy
    networks:
      - headscale-net

  hs-B:
    image: headscale-0.23-dev:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: headscale_db
      POSTGRES_USER: headscale_user
      POSTGRES_PASSWORD: 12345678 # <--- IMPORTANT: MUST MATCH THE DB PASSWORD ABOVE!
      POSTGRES_HOST: hs-db
      POSTGRES_PORT: 5432
      HEADSCALE_SERVER_URL: http://hs-1:8080 # URL for clients connecting to this instance
    volumes:
      - ./headscale_config:/etc/headscale # Shared config
      - headscale_data:/var/lib/headscale # Shared data
    ports:
      - "0.0.0.0:8081:8080" # Client port for hs-0
      - "0.0.0.0:9091:9090" # Metrics port
    command: ["headscale", "serve"]
    depends_on:
      hs-db:
        condition: service_healthy
    networks:
      - headscale-net

  ts-client-0:
    image: tailscale/tailscale:latest
    hostname: client-0
    #restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      # - ts-client-0-state:/var/lib/tailscale
      - ./tailscale_script:/etc/tailscale/script
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - HS_HOSTNAME=hs-A
    command: ["//bin/sh", "/etc/tailscale/script/run.sh"]
    depends_on:
      - hs-A
    networks:
      - headscale-net
    env_file:
      - .env

  ts-client-1:
    image: tailscale/tailscale:latest
    hostname: client-1
    #restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      # - ts-client-1-state:/var/lib/tailscale
      - ./tailscale_script:/etc/tailscale/script
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - HS_HOSTNAME=hs-B
    command: ["/bin/sh", "/etc/tailscale/script/run.sh"]
    depends_on:
      - hs-B
    networks:
      - headscale-net
    env_file:
      - .env

  ts-client-2:
    image: tailscale/tailscale:latest
    hostname: client-2
    #restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      # - ts-client-0-state:/var/lib/tailscale
      - ./tailscale_script:/etc/tailscale/script
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - HS_HOSTNAME=hs-A
    command: ["//bin/sh", "/etc/tailscale/script/run.sh"]
    depends_on:
      - hs-A
    networks:
      - headscale-net
    env_file:
      - .env

  ts-client-3:
    image: tailscale/tailscale:latest
    hostname: client-3
    #restart: unless-stopped
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      # - ts-client-1-state:/var/lib/tailscale
      - ./tailscale_script:/etc/tailscale/script
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - HS_HOSTNAME=hs-B
    command: ["/bin/sh", "/etc/tailscale/script/run.sh"]
    depends_on:
      - hs-B
    networks:
      - headscale-net
    env_file:
      - .env

volumes:
  headscale_db_data:
  headscale_data:

networks:
  headscale-net:
    driver: bridge
